import "./index.css";
import { Composition, type CalculateMetadataFunction } from "remotion";
import { MyComposition } from "./Composition";
import {
  WeeklyLineup,
  WeeklyLineupSchema,
  getCompositionDuration,
  type WeeklyLineupProps,
} from "./WeeklyLineup";
import { PullUp, PullUpSchema, PULLUP_DURATION } from "./PullUp";
import {
  ArtistRecap,
  ArtistRecapSchema,
  ARTIST_RECAP_DURATION,
} from "./ArtistRecap";
import {
  HouseWeekly,
  HouseWeeklySchema,
  HOUSEWEEKLY_DURATION,
} from "./HouseWeekly";
import recapFixture from "./audience/fixtures/recap.json";
import weeklyFixture from "./audience/fixtures/weekly.json";
import weeklyFallbackFixture from "./audience/fixtures/weekly-fallback.json";
import type { ArtistRecapProps } from "./audience/schema";

const calculateWeeklyMetadata: CalculateMetadataFunction<WeeklyLineupProps> = ({
  props,
}) => {
  return {
    durationInFrames: getCompositionDuration(props.artists.length),
  };
};

const defaultArtists: WeeklyLineupProps["artists"] = [
  {
    artistName: "Denzo",
    artistImage: "https://i.imgur.com/nt2wsuD.png",
    genre: "DJ",
    instagram: "denzo.dj",
    website: null,
    eventDate: "Thu 5 Mar",
    eventTime: "19:00",
    purpose: "Radio: Denzo",
  },
  {
    artistName: "The Silintist",
    artistImage: null,
    genre: null,
    instagram: null,
    website: "https://thesilintist.com",
    eventDate: "Fri 7 Mar",
    eventTime: "20:00",
    purpose: "Radio: Sudden Rave",
  },
];

// Demo data for PullUp - the same two artists WeeklyLineup previews with.
const defaultPullUpAvatars = [
  { label: "MZ", image: null },
  { label: "NB", image: null },
  { label: "SR", image: null },
  { label: "JV", image: null },
  { label: "KL", image: null },
  { label: "TN", image: null },
];

// The first bubble is always yours - you act before anyone else arrives.
const defaultPullUpChat = [
  { name: "you", text: "let's go Denzo!" },
  { name: "joos", text: "track 3 is nasty" },
  { name: "sef", text: "what is this??" },
];

const fallbackPullUpChat = [
  { name: "you", text: "let's go The Silintist!" },
  { name: "mira", text: "heyy \u{1F44B}" },
  { name: "roos", text: "what is this??" },
];

// Real shape, real numbers, initials only - regenerated by
// `bun scripts/fetch-audience.ts --fixtures`.
const recapProps = recapFixture as ArtistRecapProps;

// Second registration for the fallbacks the spec calls out: no artist image,
// a single session, and nobody left to count after exclusions.
const recapFallbackProps: ArtistRecapProps = {
  artistName: "The Silintist",
  artistImage: null,
  sessions: [
    {
      start: "2026-09-05T20:00:00Z",
      end: "2026-09-05T21:30:00Z",
      durationMin: 90,
      slotLabel: "Sat 8pm",
      dateLabel: "Sep 5",
      peak: 1,
      uniques: 0,
      pulled: 0,
      returning: 0,
      regulars: 0,
      crowd: 0,
      holdRate: 0,
      follows: 0,
      // Before chat capture shipped, so spoke is omitted rather than shown as 0.
      chat: null,
      quadrant: "quiet",
      shared: false,
      viewers: [],
    },
  ],
  bestUniques: 0,
  bestCrowd: 0,
  nextSlot: null,
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="MyComp"
        component={MyComposition}
        durationInFrames={450}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="WeeklyLineup"
        component={WeeklyLineup}
        schema={WeeklyLineupSchema}
        calculateMetadata={calculateWeeklyMetadata}
        durationInFrames={getCompositionDuration(defaultArtists.length)}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={{
          weekLabel: "THIS WEEK",
          dateRange: "3 - 9 March",
          artists: defaultArtists,
        }}
      />
      <Composition
        id="PullUp"
        component={PullUp}
        schema={PullUpSchema}
        durationInFrames={PULLUP_DURATION}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={{
          artistName: "Denzo",
          artistImage: "https://i.imgur.com/nt2wsuD.png",
          genre: "Dub Techno",
          eventDay: "Thu",
          eventTime: "19:00",
          eventDate: "Thu 5 Mar",
          avatars: defaultPullUpAvatars,
          chatLines: defaultPullUpChat,
          seed: 0,
          bedVariant: "b" as const,
        }}
      />
      <Composition
        id="HouseWeekly"
        component={HouseWeekly}
        schema={HouseWeeklySchema}
        durationInFrames={HOUSEWEEKLY_DURATION}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={HouseWeeklySchema.parse(weeklyFixture)}
      />
      {/* A one-show week: single board row, badges mostly unearned, no lineup
          for next week yet. The thin end of the data. */}
      <Composition
        id="HouseWeeklyFallback"
        component={HouseWeekly}
        schema={HouseWeeklySchema}
        durationInFrames={HOUSEWEEKLY_DURATION}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={HouseWeeklySchema.parse(weeklyFallbackFixture)}
      />
      {/* Second demo artist - no photo, no genre: exercises the fallbacks. */}
      <Composition
        id="PullUpFallback"
        component={PullUp}
        schema={PullUpSchema}
        durationInFrames={PULLUP_DURATION}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={{
          artistName: "The Silintist",
          artistImage: null,
          genre: null,
          eventDay: "Fri",
          eventTime: "20:00",
          eventDate: "Fri 7 Mar",
          avatars: defaultPullUpAvatars,
          chatLines: fallbackPullUpChat,
          seed: 2,
          bedVariant: "b" as const,
        }}
      />
      <Composition
        id="ArtistRecap"
        component={ArtistRecap}
        schema={ArtistRecapSchema}
        durationInFrames={ARTIST_RECAP_DURATION}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={recapProps}
      />
      {/* No photo, one session, nobody countable: exercises every fallback. */}
      <Composition
        id="ArtistRecapFallback"
        component={ArtistRecap}
        schema={ArtistRecapSchema}
        durationInFrames={ARTIST_RECAP_DURATION}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={recapFallbackProps}
      />
    </>
  );
};
